/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false .\worker-configuration-small.d.ts` (hash: ff991d4613e273a2f1f3c268aa0be89f)
interface __BaseEnv_Env {
  DB: D1Database;
  DEVICE_CODE_TTL_SECONDS: '600';
  DEVICE_POLL_INTERVAL_SECONDS: '5';
  SESSION_TTL_SECONDS: '2592000';
  ARTWORK_URL_TTL_SECONDS: '21600';
  ALLOWED_MEDIA_HOST_SUFFIXES: 'cloudflarestream.com';
  PUBLIC_ORIGIN: string;
  UPSTREAM_ORIGIN: string;
  UPSTREAM_CATALOG_PATH: string;
  ACCESS_TEAM_DOMAIN: string;
  ACCESS_AUD: string;
  ALLOWED_EMAIL_SHA256: string;
  UPSTREAM_ACCESS_CLIENT_ID: string;
  UPSTREAM_ACCESS_CLIENT_SECRET: string;
  ARTWORK_SIGNING_KEY: string;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'DEVICE_CODE_TTL_SECONDS'
        | 'DEVICE_POLL_INTERVAL_SECONDS'
        | 'SESSION_TTL_SECONDS'
        | 'ARTWORK_URL_TTL_SECONDS'
        | 'ALLOWED_MEDIA_HOST_SUFFIXES'
        | 'PUBLIC_ORIGIN'
        | 'UPSTREAM_ORIGIN'
        | 'UPSTREAM_CATALOG_PATH'
        | 'ACCESS_TEAM_DOMAIN'
        | 'ACCESS_AUD'
        | 'ALLOWED_EMAIL_SHA256'
        | 'UPSTREAM_ACCESS_CLIENT_ID'
        | 'UPSTREAM_ACCESS_CLIENT_SECRET'
        | 'ARTWORK_SIGNING_KEY'
      >
    > {}
}
